module.exports = {
  // view actions
  RESIZE_BOARD: "RESIZE_BOARD",
  // CHANGE_RESOLUTION: 'CHANGE_RESOLUTION', // TODO!
  // ADD_CONTROLS: 'ADD_CONTROLS',
  // loop actions
  START_GAME: "START_GAME",
  PAUSE_GAME: "PAUSE_GAME",
  RESUME_GAME: "RESUME_GAME",
  CHANGE_INTERVAL: "CHANGE_INTERVAL",
  // snake actions
  MOVE_FORWARD: "MOVE_FORWARD",
  ENQUEUE_TURN: "ENQUEUE_TURN"
};
